### ISSUE TITLE
Program closes when trying to change font.

### ISSUE THREAD

**Issue by BncaJrdn** [openforeveryone/WordSearchCreator#2]
I have used your software when I was a teacher. However now, it will not work.Each time I try to change the font it closes. Not really sure if this is where I post feedback and questions. Not a developer either. Ty.

**Comment by mattwellings** [comment]
Thank you for reporting this. This is definitely the place to report bugs. 
I have not seen this issue before. Could you please tell me which OS you are using and which version of the software. Also exactly when does it close for example after clicking "Text Font, Size and Colours..." on the format menu or when You click "Font..." or when you click OK on the font dialogue.
Does the issue persist if you upgrade to version 1.2.1 (which I have released since you posted this issue)?

**Comment by BncaJrdn** [comment]
Matthew,
Thank you for replying. I did not fix the issue, but my laptop died. I
bought a new one, re-downloaded your program. Is working!

Bianca
